### ISSUE TITLE
stucked when fuzz jhead

### ISSUE THREAD

**Issue by ricardo-kcc** [diewufeihong/SLIME#1]
it stucked as below when fuzz jhead using SLIME. Could anyone help me ? Thanks.
Tested env is ubuntu20.04 and clang12.0.1
![T$53@9D84QJ87`23K}5 8Y4](https://user-images.githubusercontent.com/64991294/202144806-d54e5d04-fe79-4690-9757-b84fbbd9849d.png)

**Comment by mobsceneZ** [comment]
Hello @Ricardo-609 , AFAIK, If you run `llvm_mode_crash/` related compilers under `jhead-3.04-1/` and `llvm_mode/` related compilers under `jhead-3.04-2/`, the command should be **"-H ~/Desktop/jhead-3.04-2/jhead.bb"**. Hope it helps.

**Comment by ricardo-kcc** [comment]
you are right. Thanks.
